name: Azure function test
on: push
jobs:
  azure-function-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.414"
      - run: make build/fn
