name: Dependencies
on:
  push:
  schedule:
    - cron:  '0 17 1 1-12 *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.0.2
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          renovate-version: 37.172.2
